name: package-data-example
channels:
  - defaults
  - conda-forge
  - intake

dependencies:
  - python=3.7
  - intake
  - intake-parquet
  - dask
  - pandas
  - tqdm
  - hvplot
  - s3fs>=0.3
  - anaconda-package-data
