name: package-data-example
channels:
  - conda-forge
  - defaults
  - intake

dependencies:
  - python=3.7
  - pip
  - intake
  - intake-parquet
  - dask
  - pandas
  - panel
  - tqdm
  - hvplot
  - colorcet
  - s3fs>=0.3
  - anaconda-package-data
  - pip:
    - jupyter-panel-proxy
